spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/construction_db
    username: yourusername
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Common Module
  security:
    jwt:
      secret: your_jwt_secret
      expiration: 3600000
