spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/construction_db
    username: yourusername
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Sale Service
